version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
    depends_on:
      - zookeeper

  create-topic:
    image: bitnami/kafka:3.5.1
    depends_on:
      - kafka
    entrypoint: [ "bash", "-c" ]
    command: >
      "
      sleep 20 &&
      kafka-topics.sh
        --bootstrap-server kafka:9092
        --create
        --if-not-exists
        --topic earthquakes
        --partitions 1
        --replication-factor 1
        --config cleanup.policy=compact &&
      echo '✅ Topic earthquakes with log compaction created.'
      "
